### ISSUE TITLE
yaml等のconfで設定できるオプション

### ISSUE THREAD

**Issue by shnmorimoto** [kingsang/mockun#1]
下記のようなconfで設定を指定できるオプションがあると便利だと思います。

```yaml
header:
 - content-type: xxxxxx
 - user-agent: xxxx
path:
 - /xxxx: path/xxx.json
```
